---
- name: Backup show running-config and other user level commands
  hosts: all
  gather_facts: false
  connection: local

  tasks:
   - name: show running-config
     ios_command:
      authorize: yes
      commands:
       - show run


     register: print_output

   - debug: var=print_output.stdout_lines

   - name: save output to a file
     copy: content="{{ print_output.stdout[0]}}" dest="./output/{{ inventory_hostname }}.txt" 
     